vich_uploader:
    db_driver: orm # or mongodb or phpcr
    mappings:
        resource_image:
            uri_prefix: /images/resources
            upload_destination: '%kernel.project_dir%/public/images/resources'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true